PLACEHOLDERS = {
    1: "AgACAgIAAxkBAAIVN2gHcGy6hyzU8utoe4xj4pDleY4GAALT9TEbi3U5SFXYDyyoaP3AAQADAgADbQADNgQ",
    2: "AgACAgIAAxkBAAIVLmgHWMrD_zC19HOhzJU7e-srZC_pAAIZ9TEbi3U5SJdQnqHRelyrAQADAgADbQADNgQ",
    3: "AgACAgIAAxkBAAIVOmgHcGw_w9nviO9wl1DBVlmLo87aAALU9TEbi3U5SAQ1QrKDMqXzAQADAgADbQADNgQ",
    4: "AgACAgIAAxkBAAIVO2gHcGw_KQRUUlIQ-JPD-1uPyMACAALV9TEbi3U5SF0artZA5T6gAQADAgADbQADNgQ",
    5: "AgACAgIAAxkBAAIVPGgHcGx_N5q3yYPEnAJuKctCnwuYAALX9TEbi3U5SPC8DeQSPseLAQADAgADbQADNgQ",
    6: "AgACAgIAAxkBAAIVPWgHcGy5lpcx6albXpN-UCouiW6EAALY9TEbi3U5SFGvDiHe8gYMAQADAgADbQADNgQ",
    7: "AgACAgIAAxkBAAIVPmgHcGz52opKX_iPjPYD3Hp9QeI2AALa9TEbi3U5SI548Sb9i-mOAQADAgADbQADNgQ",
    8: "AgACAgIAAxkBAAIVP2gHcGyoMGXJiZvg8CVsYyi_ULZTAALZ9TEbi3U5SEHwWSsNnGYiAQADAgADbQADNgQ",
    9: "AgACAgIAAxkBAAIVQGgHcGykMglf9dAXAaPe-JEVR5n0AALW9TEbi3U5SPRkrJNkL3WJAQADAgADbQADNgQ",
    10: "AgACAgIAAxkBAAIVOGgHcGxY5_d75lL8hHr7AmKUt3fMAALS9TEbi3U5SAMQtfz_8dSyAQADAgADbQADNgQ",

    # 1: "AgACAgIAAxkBAAICEmgKMo54kuDC1mlEriVaodNXV0SIAAKqpzEbID1RSNzD8-mM8LMTAQADAgADbQADNgQ",
    # 2: "AgACAgIAAxkBAAICE2gKMo6fPxhXFrphRR3NHkfui8_QAAKppzEbID1RSCHHtprjoJsgAQADAgADbQADNgQ",
    # 3: "AgACAgIAAxkBAAICFGgKMo72qjRNRLN8cJZzZtSC9tWJAAKrpzEbID1RSDsRXjb1l0W5AQADAgADbQADNgQ",
    # 4: "AgACAgIAAxkBAAICFWgKMo6Hb69MOINwP0Av-x4ItC9pAAKspzEbID1RSBkBIWvyoa0kAQADAgADbQADNgQ",
    # 5: "AgACAgIAAxkBAAICFmgKMo5ehYw2-6oHPA20KsNTZUgBAAKtpzEbID1RSD-Fa6N6tR7OAQADAgADbQADNgQ",
    # 6: "AgACAgIAAxkBAAICF2gKMo4zysqNqYfAFistXcn3dSYKAAKupzEbID1RSF0hGh0WMw9VAQADAgADbQADNgQ",
    # 7: "AgACAgIAAxkBAAICGGgKMo7D5zFVI_4eJhPGG_u107flAAKvpzEbID1RSDCoa8DMFAvLAQADAgADbQADNgQ",
    # 8: "AgACAgIAAxkBAAICGWgKMo4r_qJTLxBRH07a-O0EmB4vAAKwpzEbID1RSLtzQYJG0RfAAQADAgADbQADNgQ",
    # 9: "AgACAgIAAxkBAAICGmgKMo6GW2fQ-gR6ysX31CUY-T4iAAKxpzEbID1RSP_AyfyeK-PAAQADAgADbQADNgQ",
    # 10: "AgACAgIAAxkBAAICG2gKMo7edEfSiBCVh6oHkV_xOd8XAAKypzEbID1RSEh8TPzajYahAQADAgADbQADNgQ",
}


class PhotoPlaceholder:
    def __init__(self, placeholder_num):
        self.tg_id = PLACEHOLDERS[placeholder_num]
