PLACEHOLDERS = {
    1: "AgACAgIAAxkBAAIVN2gHcGy6hyzU8utoe4xj4pDleY4GAALT9TEbi3U5SFXYDyyoaP3AAQADAgADbQADNgQ",
    2: "AgACAgIAAxkBAAIVLmgHWMrD_zC19HOhzJU7e-srZC_pAAIZ9TEbi3U5SJdQnqHRelyrAQADAgADbQADNgQ",
    3: "AgACAgIAAxkBAAIVOmgHcGw_w9nviO9wl1DBVlmLo87aAALU9TEbi3U5SAQ1QrKDMqXzAQADAgADbQADNgQ",
    4: "AgACAgIAAxkBAAIVO2gHcGw_KQRUUlIQ-JPD-1uPyMACAALV9TEbi3U5SF0artZA5T6gAQADAgADbQADNgQ",
    5: "AgACAgIAAxkBAAIVPGgHcGx_N5q3yYPEnAJuKctCnwuYAALX9TEbi3U5SPC8DeQSPseLAQADAgADbQADNgQ",
    6: "AgACAgIAAxkBAAIVPWgHcGy5lpcx6albXpN-UCouiW6EAALY9TEbi3U5SFGvDiHe8gYMAQADAgADbQADNgQ",
    7: "AgACAgIAAxkBAAIVPmgHcGz52opKX_iPjPYD3Hp9QeI2AALa9TEbi3U5SI548Sb9i-mOAQADAgADbQADNgQ",
    8: "AgACAgIAAxkBAAIVP2gHcGyoMGXJiZvg8CVsYyi_ULZTAALZ9TEbi3U5SEHwWSsNnGYiAQADAgADbQADNgQ",
    9: "AgACAgIAAxkBAAIVQGgHcGykMglf9dAXAaPe-JEVR5n0AALW9TEbi3U5SPRkrJNkL3WJAQADAgADbQADNgQ",
    10: "AgACAgIAAxkBAAIVOGgHcGxY5_d75lL8hHr7AmKUt3fMAALS9TEbi3U5SAMQtfz_8dSyAQADAgADbQADNgQ",
}


class PhotoPlaceholder:
    def __init__(self, placeholder_num):
        self.tg_id = PLACEHOLDERS[placeholder_num]
