from enum import StrEnum


class MessageSticker(StrEnum):
    LOGO = 'LOGO'
    HELLO = 'HELLO'
    LOVE = 'LOVE'
    FEAR = 'FEAR'
    SAD = 'SAD'
    THINKING = 'THINKING'
    CONNECTION_ERROR = 'CONNECTION_ERROR'
    ERROR = 'ERROR'
    TEXT_GENERATION = 'TEXT_GENERATION'
    SUMMARY_GENERATION = 'SUMMARY_GENERATION'
    IMAGE_GENERATION = 'IMAGE_GENERATION'
    MUSIC_GENERATION = 'MUSIC_GENERATION'
    VIDEO_GENERATION = 'VIDEO_GENERATION'
